version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    volumes:
      # Mount a volume under the shared nginx dir to serve static files
      - ./static/:/usr/share/nginx/html/
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      # Mount the same volume to serve static files
      - ./static/:/usr/share/nginx/html/:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    ports:
      - "1883:1883" # TCP
      - "8883:8883" # Websockets
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    restart: unless-stopped
  