name: Build

on:
  push:
    branches:
      - main
      - stable
    tags:
      - v*

env:
  REGISTRY: bikenow.vkw.tu-dresden.de
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: self-hosted
    container: docker:latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
          password: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # See: https://github.com/docker/metadata-action
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
